#!/bin/bash
set -eo pipefail
[[ "${DEBUG:-}" ]] && set -x

install-osx() {
  brew cask install eclipse-jee
  export ECLIPSE_HOME="$(brew cask info eclipse-jee | grep opt | cut -f1 -d' ')/eclipse"
  sudo ln -sf "$ECLIPSE_HOME/Eclipse.app/Contents/MacOS/eclipse" /usr/bin/eclipse
}

install-linux() {
  wget -O /tmp/eclipse.tar.gz http://eclipse.c3sl.ufpr.br/technology/epp/downloads/release/luna/SR2/eclipse-jee-luna-SR2-linux-gtk-x86_64.tar.gz
  sudo tar xzvf /tmp/eclipse.tar.gz -C /opt
  export ECLIPSE_HOME="/opt/eclipse/"
  sudo chown -Rf "$(whoami)" "$ECLIPSE_HOME"
  mkdir -p  ~/.local/share/applications/
  sudo ln -sf /opt/eclipse/eclipse /usr/bin/eclipse
  wget -O ~/.local/share/applications/ \
    https://raw.githubusercontent.com/caarlos0/my-eclipse/master/eclipse.desktop
}

install() {
  if [ "$(uname -s)" = "Darwin" ]; then
    install-osx
  else
    install-linux
  fi
}

p2i() {
  local repo="$1"; shift
  eclipse -application org.eclipse.equinox.p2.director -noSplash \
    -repository "$repo" -installIUs "$*"
}

install-p2is() {
  p2i "http://update.eclemma.org/" "com.mountainminds.eclemma.feature.feature.group"
  p2i "http://eclipse.pitest.org/release" "org.pitest.pitclipse.feature.feature.group"
  p2i "http://download.eclipse.org/technology/m2e/releases/" "org.eclipse.m2e.feature.feature.group"
  p2i "http://download.jboss.org/jbosstools/updates/stable/luna/" "org.jboss.ide.eclipse.as.feature.feature.group"
}

install-lombok() {
  curl -o "$ECLIPSE_HOME"/lombok.jar http://projectlombok.org/downloads/lombok.jar
  java -jar "$ECLIPSE_HOME"/lombok.jar install "$ECLIPSE_HOME"
}

improve-eclipseini() {
  local ECLIPSE_INI="$(find "$ECLIPSE_HOME" -name eclipse.ini)"
  sed -i'' '/^--launcher.XXMaxPermSize$/{$!{N;s/256m/512m/}}' "$ECLIPSE_INI"
  sed -i'' -e 's/-Xms40m/-Xms128m/' -e 's/-Xmx512m/-Xmx2048m/' "$ECLIPSE_INI"
  echo "-Xverify:none" >> "$ECLIPSE_INI"
}

p2u() {
  eclipse -application org.eclipse.equinox.p2.director -noSplash \
    -repository http://download.eclipse.org/releases/luna/ \
    -uninstallIU "$*"
}

uninstall-plugins() {
  p2u "org.eclipse.egit.feature.group,org.eclipse.jgit.feature.group"
  p2u "org.eclipse.cvs.feature.group"
  p2u "org.eclipse.persistence.antlr,org.eclipse.persistence.asm,org.eclipse.persistence.core,org.eclipse.persistence.dbws.builder,org.eclipse.persistence.dbws,org.eclipse.persistence.jpa.jpql,org.eclipse.persistence.jpa,org.eclipse.persistence.moxy"
  p2u "org.eclipse.jpt.common.eclipselink.feature.feature.group,org.eclipse.jpt.dbws.eclipselink.feature.feature.group,org.eclipse.jpt.jpa.eclipselink.feature.feature.group"
  p2u "org.eclipse.jpt.jaxb.feature.feature.group,org.eclipse.jpt.jaxb.eclipselink.feature.feature.group"
}

install
install-lombok
install-p2is
improve-eclipseini
uninstall-plugins
