#!/bin/bash
set -eo pipefail
[[ "${DEBUG:-}" ]] && set -x

export ECLIPSE_HOME

install-osx() {
  brew cask install eclipse-jee
  ECLIPSE_HOME="$(brew cask info eclipse-jee | grep opt | cut -f1 -d' ')/eclipse"
  sudo ln -sf "$ECLIPSE_HOME/Eclipse.app/Contents/MacOS/eclipse" /usr/bin/eclipse
}

install-linux() {
  wget -c -O /tmp/eclipse.tar.gz http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/mars/2/eclipse-jee-mars-2-linux-gtk-x86_64.tar.gz
  ECLIPSE_HOME="/opt/eclipse"
  [ -d "$ECLIPSE_HOME" ] && sudo mv "$ECLIPSE_HOME" "$ECLIPSE_HOME"_backup
  sudo tar xzvf /tmp/eclipse.tar.gz -C /opt
  sudo chown -Rf "$(whoami)" "$ECLIPSE_HOME"
  mkdir -p  ~/.local/share/applications/
  sudo ln -sf /opt/eclipse/eclipse /usr/bin/eclipse
  wget -O ~/.local/share/applications/eclipse.desktop \
    https://raw.githubusercontent.com/caarlos0/my-eclipse/master/eclipse.desktop
}

install() {
  if [ "$(uname -s)" = "Darwin" ]; then
    install-osx
  else
    install-linux
  fi
}

p2i() {
  local repo="$1"; shift
  eclipse -application org.eclipse.equinox.p2.director -noSplash \
    -repository "$repo" -installIUs "$*"
}

install_p2is() {
  p2i "http://update.eclemma.org/" "com.mountainminds.eclemma.feature.feature.group"
  p2i "http://eclipse.pitest.org/release" "org.pitest.pitclipse.feature.feature.group"
  p2i "http://download.eclipse.org/technology/m2e/releases/" "org.eclipse.m2e.feature.feature.group"
  p2i "http://download.jboss.org/jbosstools/updates/stable/luna/" "org.jboss.ide.eclipse.as.feature.feature.group"
  # p2i "http://download.jboss.org/jbosstools/mars/development/updates/" "org.jboss.ide.eclipse.as.feature.feature.group"
  p2i "http://velo.github.io/maven-formatter-plugin/p2/1.5.0" "com.marvinformatics.formatter.feature.feature.group"
  p2i "http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-buildhelper/0.15.0/N/0.15.0.201405280027/" "org.sonatype.m2e.buildhelper.feature.feature.group"
  p2i "http://beust.com/eclipse/" "org.testng.eclipse.feature.group"
  p2i "http://eclipse.schedenig.name" "name.schedenig.eclipse.grepconsole.source.feature.group"
  p2i "http://download.jboss.org/jbosstools/updates/m2e-extensions/m2e-apt" "org.jboss.tools.maven.apt.feature.feature.group"
}

install_lombok() {
  curl -o "$ECLIPSE_HOME"/lombok.jar http://projectlombok.org/downloads/lombok.jar
  java -jar "$ECLIPSE_HOME"/lombok.jar install "$ECLIPSE_HOME"
}

improve_eclipseini() {
  local ECLIPSE_INI
  ECLIPSE_INI="$(find "$ECLIPSE_HOME" -name eclipse.ini)"
  sed -i'' '/^--launcher.XXMaxPermSize$/{$!{N;s/256m/512m/}}' "$ECLIPSE_INI"
  sed -i'' -e 's/-Xms40m/-Xms128m/' -e 's/-Xmx512m/-Xmx2048m/' "$ECLIPSE_INI"
  echo "-Xverify:none" >> "$ECLIPSE_INI"
}

install
install_lombok
install_p2is
improve_eclipseini
